# Workflow for generating templates and deploying to GitHub Pages
name: Generate Templates and Deploy to Pages

on:
  # Runs on pushes that modify generation scripts or source templates
  push:
    branches: ["main"]
    paths:
      - 'generation_scripts/**'
      - 'source_templates/**'
      - 'website/**'
      - '!website/config.json'
      - '!website/displayables/**'
      - '!website/downloadables/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the workflow
permissions:
  contents: write  # Need write access to commit generated files
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean generated files
        run: |
          # Remove generated files if they exist
          rm -f website/config.json
          rm -rf website/displayables
          rm -rf website/downloadables
          echo "Cleaned generated files"

      - name: Run generation script
        run: |
          cd generation_scripts
          python generate_images.py

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes to commit
          git add website/config.json website/displayables/ website/downloadables/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git commit -m "Auto-generate template variations [skip ci]"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload website directory
          path: 'website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
